### PR TITLE
Fix crazy indentation and properly recover from import

### PR DESCRIPTION
**Pull request by LambertSpot**
Addresses two issues.

**Crazy Indentation**
```
{
  "abc" : {
                   "def" : {
                                      "ghi" : "jkl"   
                                } 
               }
}
```

now becomes
```
{
  "abc" : {
     "def" : {
       "ghi" : "jkl"   
      } 
   }
}
```

**Recover from import**
```
import "../some/path" as myFunction

{
 "abc" : "def"
}
```

would highlight { with red underline and say it was not expected, because the import was not properly recovered. Adding `if` and `left curly` would at least recover import for those transformations that start with left curly or if.

### CODE REVIEW

**Review by fuchsst — APPROVED** [review]

**Comment by fuchsst** [comment]
thanks for the fixes. the plugin is updated and published and should be available within the next two days

**Comment by harmbrugge** [comment]
I'm still having these issues using the most current version of the plugin (1.0.7) from the marketplace in intellij.

**Comment by LambertSpot** [comment]
@harmbrugge for me the latest is 1.0.9 in the marketplace? 
image

**Comment by harmbrugge** [comment]
Updating to the latest version of IntelliJ made version 1.0.9 visible. All works fine now, thx

**Comment by DrGrognon** [comment]
I confirm latest version of Intellij with plugin in version 1.0.9 work perfectly :+1:

**Pull request merged**
